#include <cstring>
#include "oracle.h"
#include <bit>

SolverOracle::SolverOracle(SolverConfig cfg):cfg_(cfg),geometry_(cfg.n),solver_(cfg){}
PackedKey SolverOracle::canonicalPacked(const State& s) const{ if(cfg_.use_symmetry){ auto c=canonicalize(s, geometry_); State cs{c.key.dandelions,c.key.occupied,c.key.used_dirs}; return packStateKey(cs,cfg_.n);} return packStateKey(s,cfg_.n);} 

PlayerResult SolverOracle::evaluateP1ToMoveState(const State& state) const { if(isTerminalWin(state,geometry_)) return PlayerResult::P1; if(isTerminalLoss(state,cfg_.k)) return PlayerResult::P2; auto lr=solver_.memo().find(canonicalPacked(state)); if(lr==LookupResult::FoundP1) return PlayerResult::P1; if(lr==LookupResult::FoundP2) return PlayerResult::P2; return PlayerResult::Unknown; }
PlayerResult SolverOracle::solveP1ToMoveState(const State& state){ auto r=solver_.solveFromState(state); return r.complete ? (r.first_wins?PlayerResult::P1:PlayerResult::P2) : PlayerResult::Unknown; }

PlayerResult SolverOracle::evaluateP2ToBlowState(const State& state) const { bool hasUnknown=false; for(int d=0;d<8;++d) if(!(state.used_dirs&(1u<<d))){ auto nx=applyWind(state,d,geometry_); auto e=evaluateP1ToMoveState(nx); if(e==PlayerResult::P2) return PlayerResult::P2; if(e==PlayerResult::Unknown) hasUnknown=true; } return hasUnknown?PlayerResult::Unknown:PlayerResult::P1; }
PlayerResult SolverOracle::solveP2ToBlowState(const State& state){ bool hasUnknown=false; for(int d=0;d<8;++d) if(!(state.used_dirs&(1u<<d))){ auto nx=applyWind(state,d,geometry_); auto e=evaluateP1ToMoveState(nx); if(e==PlayerResult::Unknown){ e=solveP1ToMoveState(nx); } if(e==PlayerResult::P2) return PlayerResult::P2; if(e==PlayerResult::Unknown) hasUnknown=true; } return hasUnknown?PlayerResult::Unknown:PlayerResult::P1; }

std::vector<MoveEvaluation> SolverOracle::listP1Moves(const State& s) const { std::vector<MoveEvaluation> out; uint64_t pm=plantableMask(s,geometry_); while(pm){ int c=std::countr_zero(pm); pm&=pm-1; MoveEvaluation me; auto xy=geometry_.coord(c); me.move_label="("+std::to_string(xy.x)+","+std::to_string(xy.y)+")"; State ap=applyPlant(s,c); if(isTerminalWin(ap,geometry_)){ me.result=PlayerResult::P1; out.push_back(me); continue;} bool unknown=false; bool p2=false; for(int d=0;d<8;++d) if(!(ap.used_dirs&(1u<<d))){ auto nx=applyWind(ap,d,geometry_); auto e=evaluateP1ToMoveState(nx); if(e==PlayerResult::P2){ p2=true; me.refuting_dirs.push_back(d);} else if(e==PlayerResult::Unknown){ unknown=true; me.unknown_dirs.push_back(d);} }
 if(p2) me.result=PlayerResult::P2; else if(unknown) me.result=PlayerResult::Unknown; else me.result=PlayerResult::P1; out.push_back(me);} return out; }
std::vector<MoveEvaluation> SolverOracle::listP2Moves(const State& s) const { std::vector<MoveEvaluation> out; for(int d=0;d<8;++d) if(!(s.used_dirs&(1u<<d))){ MoveEvaluation me; static const char* nm[8]={"E","W","N","S","NE","NW","SE","SW"}; me.move_label=nm[d]; auto nx=applyWind(s,d,geometry_); me.result=evaluateP1ToMoveState(nx); out.push_back(me);} return out; }

bool SolverOracle::saveMemo(const std::string& path, bool complete, uint8_t root_result) const { MemoFileHeader h{}; std::memcpy(h.magic,"DSMEM01",8); h.file_version=1; h.n=static_cast<uint8_t>(cfg_.n); h.k=static_cast<uint8_t>(cfg_.k); h.rules_version=1; h.direction_scheme=1; h.key_format=cfg_.n==6?2:1; h.canonical_keys=cfg_.use_symmetry?1:0; h.db_scope=2; h.complete=complete?1:0; h.rules_hash=0xD011AULL; h.hash_seed=0x726f6f7448617368ULL; h.hash_version=1; h.bucket_capacity=solver_.memo().capacity(); h.entries_count=solver_.memo().size(); h.root_result=root_result; return saveMemoFile(path,h,solver_.memo()); }
bool SolverOracle::loadMemo(const std::string& path, std::string& err) { MemoFileHeader h{}; MemoTable t(cfg_.n==6); if(!loadMemoFile(path,h,t,err)) return false; if(h.n!=cfg_.n||h.k!=cfg_.k){ err="n/k mismatch"; return false;} if(h.key_format!=(cfg_.n==6?2:1)){ err="key format mismatch"; return false;} solver_.memo() = std::move(t); return true; }
